config/routes.rb
Shoelaces::Application.routes.draw do
  resources :somethings
  root :to => 'somethings#index'

end

app/models/something.rb
class Something < ActiveRecord::Base
  mount_uploader :something, SomethingUploader
  attr_accessor :shoelace
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/somethings_controller.rb
class SomethingsController < ApplicationController
  # GET /somethings
  # GET /somethings.xml
  def index
    @somethings = Something.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @somethings }
    end
  end

  # GET /somethings/1
  # GET /somethings/1.xml
  def show
    @something = Something.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @something }
    end
  end

  # GET /somethings/new
  # GET /somethings/new.xml
  def new
    @something = Something.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @something }
    end
  end

  # POST /somethings
  # POST /somethings.xml
  def create
    something = params[:something].delete :something
    @something = Something.new(params[:something])
    @something.ip_address = request.remote_ip
    @something.something = something
    respond_to do |format|
      if @something.save
        format.html { redirect_to(@something, :notice => 'Your shoelace was successfully created.') }
        format.xml  { render :xml => @something, :status => :created, :location => @something }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @something.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /somethings/1
  # PUT /somethings/1.xml
  def update
    @something = Something.find(params[:id])

    respond_to do |format|
      if @something.update_attributes(params[:something])
        redirect_to(@something, :notice => 'Your shoelace was updated.')
      else
        render :action => "edit"
      end
    end
  end

  # DELETE /somethings/1
  # DELETE /somethings/1.xml
  def destroy
    @something = Something.find(params[:id])
    @something.destroy

    redirect_to somethings_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def background
    colors = ['416672','5a8696','a5869c','738c5a','3f6571','4d656f','129a7e','1e6481','e9dcd5','81965e','3f3f0f','2a574d','a85819','848e4a','102f3b','443051','166354','bcc157','496e54','c4cb9e','bee4ea']

    raw("<style type='text/css'>body{background: \##{colors[rand(colors.count)]};}</style>")
  end
end

app/helpers/somethings_helper.rb
module SomethingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Shoelaces For Everything</title>
      <% if RAILS_ENV == 'production' %>
        <%= stylesheet_link_tag 'style' %>
      <% else %>
        <link rel='stylesheet/less' href='/stylesheets/style.less' type='text/css' />
        <script src='/javascripts/less.min.js'></script>
        <script type='text/javascript' charset='utf-8'>
          less.env = 'development';
          less.watch();
        </script>
      <% end %>
      <%= background %>
      <%= javascript_include_tag :defaults %>
      <%= javascript_include_tag 'plupload.full.min.js' %>
      <%= javascript_include_tag 'application' %>
      <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="bodyFlash"></div>
    <div id='flashNotice' style='display: none'><%= flash[:notice] if flash[:notice] %></div>
    <div id='flashError' style='display: none'><%= flash[:error] if flash[:error] %></div>
    <% flash[:error] = '' %>
    <% flash[:notice] = '' %>
    <div class="centered">
      <div id="bg">
        <div id="logo" class="outer">
          <%= link_to image_tag('logo2.png'), somethings_url, :class => 'inner' %>
        </div>
        <%= yield %>
      </div>
    </div>
    <div class="break"></div>
  </body>
</html>

app/views/somethings/index.html.erb
<div class="break">
  <br><%= link_to 'Just Shoe It', new_something_path, :class => 'button' %>
</div>
<div id="somethings">
  <% @somethings.reverse.each_slice(3).each do |somethingRow| %>
    <div class="row">
      <% somethingRow.each do |something| %>
        <div class="somethingWrapper">
          <h2>Shoelaces For <%= something.title %></h2>
          <div class="thumb">
            <%= link_to image_tag(something.something.thumb.url), something %>
            <%#= image_tag something.something.url %>
          </div>
          <div class="controls">
            <div class="outer">
              <div class="inner">
                <span><%= link_to 'Bigger', something %></span>
                <%# show the delete link if you made it %>
                <% if something.ip_address == request.remote_ip %>
                  <span>|&nbsp;<%= link_to 'Delete', something, :confirm => 'You sure about that?', :method => :delete %></span>
                <% end %>
                <span>
                  |&nbsp;by <%= something.name? ? something.name : 'anon' %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="copyright">
  &copy; <%= Date.today.year %> Reducify
</div>

app/views/somethings/new.html.erb
<div id="new">
  <%= form_for @something, :html => {:multipart => true} do |f| %>
    <div id="inputs">
      <%#= f.label :email %>
      <%#= f.text_field :email %>
      <%#= f.label :description %>
      <%#= f.text_area :description %>
      <div class="formSection">
        <%= f.label :something, 'Choose an image:' %>
        <br><%= f.file_field :something %>
        <div id="imageError" class="error"><br><span></span></div>
      </div>
      <div class="formSection">
        <%= f.label :title, 'This is a picture of:' %>
        <br><%= f.text_field :title, :class => 'text' %>
        <br><span class="example">e.g. cars, a banana split, canoeing</span>
        <div id="titleError" class="error"><br><span></span></div>
      </div>
      <div class="formSection">
        <label class="floatClear">Pick your shoelace:</label>
        <div id="shoelaceForm">
          <% (1..4).to_a.each do |number| %>
            <label>
              <%= f.radio_button 'shoelace', number %>
              <%= image_tag "shoelaces/thumbs/#{number}.png", :class => 'shoelaceThumb', :id => "shoelaceThumb#{number}" %>
            </label>
          <% end %>
        </div>
        <div id="shoelaceError" class="error"><br><span></span></div>
      </div>
      <div class="formSection">
        <%= f.label :name, 'What\'s your name? (optional):' %>
        <br><%= f.text_field :name, :class => 'text' %>
      </div>
    </div>
    <div class="actions">
      <a href="#" class="button formSubmit">Make Your Shoelace</a>
      <%= link_to 'Cancel', somethings_path, :class => 'cancel' %>
      <%= f.submit :style => 'display: none' %>
    </div>
  <% end %>
</div>

app/views/somethings/show.html.erb
<div id="show">
  <h1>Shoelaces For <%= @something.title %></h1>
  <div class="controls">
    <div class="outer">
      <div class="inner">
        <%# show the edit link only if you made it (ie, if the ips match) %>
        <% if @something.ip_address == request.remote_ip %>
          <span><%= link_to 'Delete', @something, :confirm => 'You sure about that?', :method => :delete %>&nbsp;|</span>
        <% end %>
        <span><%= link_to 'Back', somethings_path %>&nbsp;|</span>
        <span>
          by <%= @something.name? ? @something.name : 'anon' %>
        </span>
      </div>
    </div>
  </div>
  <div class="outer">
    <%= image_tag @something.something.url, :class => 'inner' %>
  </div>
</div>